Multi User Multi Touch Exercise: TUIO::TuioClient Class Reference
TUIO::TuioClient Class Reference
#include <TuioClient.h>
Public Member Functions
TuioClient ()
TuioClient (int port)
TuioClient (OscReceiver *oscreceiver)
~TuioClient ()
void connect (bool lock=false)
void disconnect ()
bool isConnected ()
std::list< TuioObject * > getTuioObjects ()
std::list< TuioObject * > getTuioObjects (int source_id)
std::list< TuioObject > copyTuioObjects (int source_id)
std::list< TuioObject > copyTuioObjects ()
TuioObject * getTuioObject (long s_id)
TuioObject * getTuioObject (int src_id, long s_id)
std::list< TuioCursor * > getTuioCursors ()
std::list< TuioCursor * > getTuioCursors (int source_id)
std::list< TuioCursor > copyTuioCursors ()
std::list< TuioCursor > copyTuioCursors (int source_id)
TuioCursor * getTuioCursor (long s_id)
TuioCursor * getTuioCursor (int src_id, long s_id)
std::list< TuioBlob * > getTuioBlobs ()
std::list< TuioBlob * > getTuioBlobs (int source_id)
std::list< TuioBlob > copyTuioBlobs ()
std::list< TuioBlob > copyTuioBlobs (int source_id)
TuioBlob * getTuioBlob (long s_id)
TuioBlob * getTuioBlob (int src_id, long s_id)
void processOSC (const osc::ReceivedMessage &message)
void addTuioListener (TuioListener *listener)
void removeTuioListener (TuioListener *listener)
void removeAllTuioListeners ()
int getTuioObjectCount ()
int getTuioCursorCount ()
int getTuioBlobCount ()
void lockObjectList ()
void unlockObjectList ()
void lockCursorList ()
void unlockCursorList ()
void lockBlobList ()
void unlockBlobList ()
Protected Attributes
std::list< TuioListener * > listenerList
std::list< TuioObject * > objectList
std::list< TuioCursor * > cursorList
std::list< TuioBlob * > blobList
pthread_mutex_t objectMutex
pthread_mutex_t cursorMutex
pthread_mutex_t blobMutex
Detailed Description
The TuioClient class is the central TUIO protocol decoder component. It provides a simple callback infrastructure using the TuioListener interface. In order to receive and decode TUIO messages an instance of TuioClient needs to be created. The TuioClient instance then generates TUIO events which are broadcasted to all registered classes that implement the TuioListener interface.
TuioClient *client = new TuioClient();
client->addTuioListener(myTuioListener);
client->connect();
Author
Martin Kaltenbrunner
Version
1.1.6
Definition at line 50 of file TuioClient.h.
Constructor & Destructor Documentation
TuioClient() [1/3]
TuioClient::TuioClient ()
This constructor creates a TuioClient that uses an internal UdpReceiver listening to the default UDP port 3333
Definition at line 26 of file TuioClient.cpp.
TuioClient() [2/3]
TuioClient::TuioClient (int port)
This constructor creates a TuioClient that uses an internal UdpReceiver listening to the provided UDP port
Parameters
port the UDP port the internal UdpReceiver is listening to
Definition at line 37 of file TuioClient.cpp.
TuioClient() [3/3]
TuioClient::TuioClient (OscReceiver * oscreceiver)
This constructor creates a TuioClient that uses the provided OscReceiver for the incoming OSC data
Parameters
oscreceiver the OscReceiver implementation for the chosen transport method (UDP, TCP ...)
Definition at line 48 of file TuioClient.cpp.
~TuioClient()
TuioClient::~TuioClient ()
The destructor is doing nothing in particular.
Definition at line 65 of file TuioClient.cpp.
Member Function Documentation
addTuioListener()
void TuioDispatcher::addTuioListener (TuioListener * listener) inherited
Adds the provided TuioListener to the list of registered TUIO event listeners
Parameters
listener the TuioListener to add
Definition at line 101 of file TuioDispatcher.cpp.
connect()
void TuioClient::connect (bool lock = false)
The TuioClient connects and starts receiving TUIO messages from its associated OscReceiver
Parameters
lock running in the background if set to false (default)
Definition at line 704 of file TuioClient.cpp.
References TUIO::OscReceiver::connect(), TUIO::TuioTime::initSession(), TUIO::TuioTime::reset(), TUIO::TuioDispatcher::unlockBlobList(), TUIO::TuioDispatcher::unlockCursorList(), and TUIO::TuioDispatcher::unlockObjectList().
copyTuioBlobs() [1/2]
std::list<TuioBlob> TUIO::TuioClient::copyTuioBlobs () inline
Returns a List with a copy of all currently active TuioBlobs
Returns
a List with a copy of TuioBlobs
Definition at line 236 of file TuioClient.h.
References TUIO::TuioDispatcher::copyTuioBlobs().
copyTuioBlobs() [2/2]
std::list< TuioBlob > TuioClient::copyTuioBlobs (int source_id)
Returns a List with a copy of all currently active TuioBlobs which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List with a copy of TuioBlobs
Definition at line 839 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
copyTuioCursors() [1/2]
std::list<TuioCursor> TUIO::TuioClient::copyTuioCursors () inline
Returns a List with a copy of all currently active TuioCursors
Returns
a List with a copy of TuioCursors
Definition at line 178 of file TuioClient.h.
References TUIO::TuioDispatcher::copyTuioCursors().
copyTuioCursors() [2/2]
std::list< TuioCursor > TuioClient::copyTuioCursors (int source_id)
Returns a List with a copy of all currently active TuioCursors which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List with a copy of TuioCursors
Definition at line 828 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
copyTuioObjects() [1/2]
std::list<TuioObject> TUIO::TuioClient::copyTuioObjects () inline
Returns a List with a copy of all currently active TuioObjects
Returns
a List with a copy of TuioObjects
Definition at line 129 of file TuioClient.h.
References TUIO::TuioDispatcher::copyTuioObjects().
copyTuioObjects() [2/2]
std::list< TuioObject > TuioClient::copyTuioObjects (int source_id)
Returns a List with a copy of all currently active TuioObjects which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List with a copy of TuioObjects
Definition at line 817 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
disconnect()
void TuioClient::disconnect ()
The TuioClient disconnects and stops receiving TUIO messages from its associated OscReceiver
Definition at line 716 of file TuioClient.cpp.
References TUIO::OscReceiver::disconnect().
getTuioBlob() [1/2]
TuioBlob * TuioClient::getTuioBlob (int src_id, long s_id)
Returns the TuioBlob corresponding to the provided Session ID which is associated to the given Source ID or NULL if the Session ID does not refer to an active TuioBlob
Parameters
src_id the source ID of the corresponding TUIO source
s_id the session ID of the corresponding TuioBlob
Returns
an active TuioBlob corresponding to the provided Session ID or NULL
Definition at line 770 of file TuioClient.cpp.
References TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
getTuioBlob() [2/2]
TuioBlob* TUIO::TuioClient::getTuioBlob (long s_id) inline
Returns the TuioBlob corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioBlob
Parameters
s_id the session ID of the corresponding TuioBlob
Returns
an active TuioBlob corresponding to the provided Session ID or NULL
Definition at line 256 of file TuioClient.h.
getTuioBlobCount()
int TuioDispatcher::getTuioBlobCount () inherited
Returns the number of all currently active TuioBlobs
Returns
the of all currently active TuioBlobs
Definition at line 185 of file TuioDispatcher.cpp.
getTuioBlobs() [1/2]
std::list<TuioBlob*> TUIO::TuioClient::getTuioBlobs () inline
Returns a List of all currently active TuioBlobs
Returns
a List of TuioBlobs
Definition at line 218 of file TuioClient.h.
References TUIO::TuioDispatcher::getTuioBlobs().
getTuioBlobs() [2/2]
std::list< TuioBlob * > TuioClient::getTuioBlobs (int source_id)
Returns a List of all currently active TuioBlobs which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List of TuioBlobs
Definition at line 805 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
getTuioCursor() [1/2]
TuioCursor * TuioClient::getTuioCursor (int src_id, long s_id)
Returns the TuioCursor corresponding to the provided Session ID which is associated to the given Source ID or NULL if the Session ID does not refer to an active TuioCursor
Parameters
src_id the source ID of the corresponding TUIO source
s_id the session ID of the corresponding TuioCursor
Returns
an active TuioCursor corresponding to the provided Session ID or NULL
Definition at line 758 of file TuioClient.cpp.
References TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
getTuioCursor() [2/2]
TuioCursor* TUIO::TuioClient::getTuioCursor (long s_id) inline
Returns the TuioCursor corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioCursor
Parameters
s_id the session ID of the corresponding TuioCursor
Returns
an active TuioCursor corresponding to the provided Session ID or NULL
Definition at line 198 of file TuioClient.h.
getTuioCursorCount()
int TuioDispatcher::getTuioCursorCount () inherited
Returns the number of all currently active TuioCursors
Returns
the of all currently active TuioCursors
Definition at line 181 of file TuioDispatcher.cpp.
getTuioCursors() [1/2]
std::list<TuioCursor*> TUIO::TuioClient::getTuioCursors () inline
Returns a List of all currently active TuioCursors
Returns
a List of TuioCursors
Definition at line 160 of file TuioClient.h.
References TUIO::TuioDispatcher::getTuioCursors().
getTuioCursors() [2/2]
std::list< TuioCursor * > TuioClient::getTuioCursors (int source_id)
Returns a List of all currently active TuioCursors which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List of TuioCursors
Definition at line 794 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
getTuioObject() [1/2]
TuioObject * TuioClient::getTuioObject (int src_id, long s_id)
Returns the TuioObject corresponding to the provided Session ID which is associated to the given Source ID or NULL if the Session ID does not refer to an active TuioObject
Parameters
src_id the source ID of the corresponding TUIO source
s_id the session ID of the corresponding TuioObject
Returns
an active TuioObject corresponding to the provided Session ID or NULL
Definition at line 746 of file TuioClient.cpp.
References TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
getTuioObject() [2/2]
TuioObject* TUIO::TuioClient::getTuioObject (long s_id) inline
Returns the TuioObject corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioObject
Parameters
s_id the session ID of the corresponding TuioObject
Returns
an active TuioObject corresponding to the provided Session ID or NULL
Definition at line 140 of file TuioClient.h.
getTuioObjectCount()
int TuioDispatcher::getTuioObjectCount () inherited
Returns the number of all currently active TuioObjects
Returns
the of all currently active TuioObjects
Definition at line 177 of file TuioDispatcher.cpp.
getTuioObjects() [1/2]
std::list<TuioObject*> TUIO::TuioClient::getTuioObjects () inline
Returns a List of all currently active TuioObjects
Returns
a List of TuioObjects
Definition at line 101 of file TuioClient.h.
References TUIO::TuioDispatcher::getTuioObjects().
getTuioObjects() [2/2]
std::list< TuioObject * > TuioClient::getTuioObjects (int source_id)
Returns a List of all currently active TuioObjects which are associated to the given Source ID
Parameters
src_id the source ID of the corresponding TUIO source
Returns
a List of TuioObjects
Definition at line 783 of file TuioClient.cpp.
References TUIO::TuioContainer::getTuioSourceID(), TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
isConnected()
bool TuioClient::isConnected ()
Returns true if this TuioClient is currently connected.
Returns
true if this TuioClient is currently connected
Definition at line 700 of file TuioClient.cpp.
References TUIO::OscReceiver::isConnected().
lockBlobList()
void TuioDispatcher::lockBlobList () inherited
Locks the TuioBlob list in order to avoid updates during access
Definition at line 85 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioBlobs(), copyTuioBlobs(), getTuioBlob(), TUIO::TuioDispatcher::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlobs(), and getTuioBlobs().
lockCursorList()
void TuioDispatcher::lockCursorList () inherited
Locks the TuioCursor list in order to avoid updates during access
Definition at line 69 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioCursors(), copyTuioCursors(), getTuioCursor(), TUIO::TuioDispatcher::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursors(), and getTuioCursors().
lockObjectList()
void TuioDispatcher::lockObjectList () inherited
Locks the TuioObject list in order to avoid updates during access
Definition at line 53 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioObjects(), copyTuioObjects(), getTuioObject(), TUIO::TuioDispatcher::getTuioObject(), TUIO::TuioDispatcher::getTuioObjects(), and getTuioObjects().
removeAllTuioListeners()
void TuioDispatcher::removeAllTuioListeners () inherited
Removes all TuioListener from the list of registered TUIO event listeners
Definition at line 110 of file TuioDispatcher.cpp.
removeTuioListener()
void TuioDispatcher::removeTuioListener (TuioListener * listener) inherited
Removes the provided TuioListener from the list of registered TUIO event listeners
Parameters
listener the TuioListener to remove
Definition at line 105 of file TuioDispatcher.cpp.
unlockBlobList()
void TuioDispatcher::unlockBlobList () inherited
Releases the lock of the TuioBlob list
Definition at line 93 of file TuioDispatcher.cpp.
Referenced by connect(), TUIO::TuioDispatcher::copyTuioBlobs(), copyTuioBlobs(), getTuioBlob(), TUIO::TuioDispatcher::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlobs(), and getTuioBlobs().
unlockCursorList()
void TuioDispatcher::unlockCursorList () inherited
Releases the lock of the TuioCursor list
Definition at line 77 of file TuioDispatcher.cpp.
Referenced by connect(), TUIO::TuioDispatcher::copyTuioCursors(), copyTuioCursors(), getTuioCursor(), TUIO::TuioDispatcher::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursors(), and getTuioCursors().
unlockObjectList()
void TuioDispatcher::unlockObjectList () inherited
Releases the lock of the TuioObject list
Definition at line 61 of file TuioDispatcher.cpp.
Referenced by connect(), TUIO::TuioDispatcher::copyTuioObjects(), copyTuioObjects(), getTuioObject(), TUIO::TuioDispatcher::getTuioObject(), TUIO::TuioDispatcher::getTuioObjects(), and getTuioObjects().
The documentation for this class was generated from the following files:
vendor/TUIO/TUIO/TuioClient.h
vendor/TUIO/TUIO/TuioClient.cpp