Multi User Multi Touch Exercise: TUIO::TuioManager Class Reference
TUIO::TuioManager Class Reference
#include <TuioManager.h>
Public Member Functions
TuioManager ()
~TuioManager ()
TuioObject * addTuioObject (int sym, float xp, float yp, float a)
void updateTuioObject (TuioObject *tobj, float xp, float yp, float a)
void removeTuioObject (TuioObject *tobj)
void addExternalTuioObject (TuioObject *tobj)
void updateExternalTuioObject (TuioObject *tobj)
void removeExternalTuioObject (TuioObject *tobj)
TuioCursor * addTuioCursor (float xp, float yp)
void updateTuioCursor (TuioCursor *tcur, float xp, float yp)
void removeTuioCursor (TuioCursor *tcur)
void addExternalTuioCursor (TuioCursor *tcur)
void updateExternalTuioCursor (TuioCursor *tcur)
void removeExternalTuioCursor (TuioCursor *tcur)
TuioBlob * addTuioBlob (float xp, float yp, float angle, float width, float height, float area)
void updateTuioBlob (TuioBlob *tblb, float xp, float yp, float angle, float width, float height, float area)
void removeTuioBlob (TuioBlob *tblb)
void addExternalTuioBlob (TuioBlob *tblb)
void updateExternalTuioBlob (TuioBlob *tblb)
void removeExternalTuioBlob (TuioBlob *tblb)
void initFrame (TuioTime ttime)
void commitFrame ()
long getSessionID ()
long getFrameID ()
TuioTime getFrameTime ()
std::list< TuioObject * > getUntouchedObjects ()
std::list< TuioCursor * > getUntouchedCursors ()
std::list< TuioBlob * > getUntouchedBlobs ()
void stopUntouchedMovingObjects ()
void stopUntouchedMovingCursors ()
void stopUntouchedMovingBlobs ()
void removeUntouchedStoppedObjects ()
void removeUntouchedStoppedCursors ()
void removeUntouchedStoppedBlobs ()
TuioObject * getClosestTuioObject (float xp, float yp)
TuioCursor * getClosestTuioCursor (float xp, float yp)
TuioBlob * getClosestTuioBlob (float xp, float yp)
void setVerbose (bool verbose)
bool isVerbose ()
void setInversion (bool ix, bool iy, bool ia)
void setInvertXpos (bool ix)
void setInvertYpos (bool iy)
void setInvertAngle (bool ia)
bool getInvertXpos ()
bool getInvertYpos ()
bool getInvertAngle ()
void resetTuioObjects ()
void resetTuioCursors ()
void resetTuioBlobs ()
void addTuioListener (TuioListener *listener)
void removeTuioListener (TuioListener *listener)
void removeAllTuioListeners ()
std::list< TuioObject * > getTuioObjects ()
int getTuioObjectCount ()
std::list< TuioObject > copyTuioObjects ()
std::list< TuioCursor * > getTuioCursors ()
int getTuioCursorCount ()
std::list< TuioCursor > copyTuioCursors ()
std::list< TuioBlob * > getTuioBlobs ()
int getTuioBlobCount ()
std::list< TuioBlob > copyTuioBlobs ()
TuioObject * getTuioObject (long s_id)
TuioCursor * getTuioCursor (long s_id)
TuioBlob * getTuioBlob (long s_id)
void lockObjectList ()
void unlockObjectList ()
void lockCursorList ()
void unlockCursorList ()
void lockBlobList ()
void unlockBlobList ()
Protected Attributes
std::list< TuioCursor * > freeCursorList
std::list< TuioCursor * > freeCursorBuffer
std::list< TuioBlob * > freeBlobList
std::list< TuioBlob * > freeBlobBuffer
TuioTime currentFrameTime
long currentFrame
int maxCursorID
int maxBlobID
long sessionID
bool updateObject
bool updateCursor
bool updateBlob
bool verbose
bool invert_x
bool invert_y
bool invert_a
std::list< TuioListener * > listenerList
std::list< TuioObject * > objectList
std::list< TuioCursor * > cursorList
std::list< TuioBlob * > blobList
pthread_mutex_t objectMutex
pthread_mutex_t cursorMutex
pthread_mutex_t blobMutex
Detailed Description
The TuioManager class is the central TUIO session management component.
During runtime the each frame is marked with the initFrame and commitFrame methods, while the currently present TuioObjects are managed by the server with ADD, UPDATE and REMOVE methods in analogy to the TuioClient's TuioListener interface.
TuioManager *manager = new TuioManager();
...
server->initFrame(TuioTime::getSessionTime());
TuioObject *tobj = server->addTuioObject(xpos,ypos, angle);
TuioCursor *tcur = server->addTuioObject(xpos,ypos);
TuioBlob *tblb = server->addTuioBlob(xpos,ypos,width,height,angle);
server->commitFrame();
...
server->initFrame(TuioTime::getSessionTime());
server->updateTuioObject(tobj, xpos,ypos, angle);
server->updateTuioCursor(tcur, xpos,ypos);
server->updateTuioBlob(tblb, xpos,ypos,width,height,angle);
server->commitFrame();
...
server->initFrame(TuioTime::getSessionTime());
server->removeTuioObject(tobj);
server->removeTuioCursor(tcur);
server->removeTuioBlob(tblb);
server->commitFrame();
Author
Martin Kaltenbrunner
Version
1.1.6
Definition at line 62 of file TuioManager.h.
Constructor & Destructor Documentation
TuioManager()
TuioManager::TuioManager ()
The default constructor creates a TuioManager
Definition at line 23 of file TuioManager.cpp.
~TuioManager()
TuioManager::~TuioManager ()
The destructor is doing nothing in particular.
Definition at line 40 of file TuioManager.cpp.
Member Function Documentation
addExternalTuioBlob()
void TuioManager::addExternalTuioBlob (TuioBlob * tblb)
Updates an externally managed TuioBlob
Parameters
tblb the TuioBlob to update
Definition at line 289 of file TuioManager.cpp.
References TUIO::TuioBlob::getAngle(), TUIO::TuioBlob::getArea(), TUIO::TuioBlob::getBlobID(), TUIO::TuioBlob::getHeight(), TUIO::TuioContainer::getSessionID(), TUIO::TuioBlob::getWidth(), TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), TUIO::TuioBlob::setBlobID(), and TUIO::TuioContainer::setSessionID().
addExternalTuioCursor()
void TuioManager::addExternalTuioCursor (TuioCursor * tcur)
Adds an externally managed TuioCursor
Parameters
tcur the TuioCursor to add
Definition at line 158 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), and TUIO::TuioContainer::setSessionID().
addExternalTuioObject()
void TuioManager::addExternalTuioObject (TuioObject * tobj)
Adds an externally managed TuioObject to the TuioServer's internal list of active TuioObjects
Parameters
tobj the TuioObject to add
Definition at line 59 of file TuioManager.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), and TUIO::TuioContainer::setSessionID().
addTuioBlob()
TuioBlob * TuioManager::addTuioBlob (float xp, float yp, float angle, float width, float height, float area)
Creates a new TuioBlob based on the given arguments. The new TuioBlob is added to the TuioServer's internal list of active TuioBlobs and a reference is returned to the caller.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
angle the angle to assign
width the width to assign
height the height to assign
area the area to assign
Returns
reference to the created TuioBlob
Definition at line 259 of file TuioManager.cpp.
References TUIO::TuioBlob::getAngle(), TUIO::TuioBlob::getArea(), TUIO::TuioBlob::getBlobID(), TUIO::TuioBlob::getHeight(), TUIO::TuioContainer::getSessionID(), TUIO::TuioBlob::getWidth(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
addTuioCursor()
TuioCursor * TuioManager::addTuioCursor (float xp, float yp)
Creates a new TuioCursor based on the given arguments. The new TuioCursor is added to the TuioServer's internal list of active TuioCursors and a reference is returned to the caller.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
Returns
reference to the created TuioCursor
Definition at line 128 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
addTuioListener()
void TuioDispatcher::addTuioListener (TuioListener * listener) inherited
Adds the provided TuioListener to the list of registered TUIO event listeners
Parameters
listener the TuioListener to add
Definition at line 101 of file TuioDispatcher.cpp.
addTuioObject()
TuioObject * TuioManager::addTuioObject (int sym, float xp, float yp, float a)
Creates a new TuioObject based on the given arguments. The new TuioObject is added to the TuioServer's internal list of active TuioObjects and a reference is returned to the caller.
Parameters
sym the Symbol ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
Returns
reference to the created TuioObject
Definition at line 44 of file TuioManager.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
commitFrame()
void TuioManager::commitFrame ()
Commits the current frame. Generates and sends TUIO messages of all currently active and updated TuioObjects and TuioCursors.
Definition at line 426 of file TuioManager.cpp.
Referenced by TUIO::TuioServer::commitFrame().
copyTuioBlobs()
std::list< TuioBlob > TuioDispatcher::copyTuioBlobs () inherited
Returns a List with a copy of currently active TuioBlobs
Returns
a List with a copy of all currently active TuioBlobs
Definition at line 212 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
Referenced by TUIO::TuioClient::copyTuioBlobs().
copyTuioCursors()
std::list< TuioCursor > TuioDispatcher::copyTuioCursors () inherited
Returns a List with a copy of currently active TuioCursors
Returns
a List with a copy of all currently active TuioCursors
Definition at line 200 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
Referenced by TUIO::TuioClient::copyTuioCursors().
copyTuioObjects()
std::list< TuioObject > TuioDispatcher::copyTuioObjects () inherited
Returns a List with a copy of currently active TuioObjects
Returns
a List with a copy of all currently active TuioObjects
Definition at line 189 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
Referenced by TUIO::TuioClient::copyTuioObjects().
getClosestTuioBlob()
TuioBlob * TuioManager::getClosestTuioBlob (float xp, float yp)
Returns the TuioBlob closest to the provided coordinates or NULL if there isn't any active TuioBlob
Returns
the closest TuioBlob corresponding to the provided coordinates or NULL
Definition at line 463 of file TuioManager.cpp.
References TUIO::TuioPoint::getDistance().
getClosestTuioCursor()
TuioCursor * TuioManager::getClosestTuioCursor (float xp, float yp)
Returns the TuioCursor closest to the provided coordinates or NULL if there isn't any active TuioCursor
Returns
the closest TuioCursor corresponding to the provided coordinates or NULL
Definition at line 447 of file TuioManager.cpp.
References TUIO::TuioPoint::getDistance().
getClosestTuioObject()
TuioObject * TuioManager::getClosestTuioObject (float xp, float yp)
Returns the TuioObject closest to the provided coordinates or NULL if there isn't any active TuioObject
Returns
the closest TuioObject to the provided coordinates or NULL
Definition at line 431 of file TuioManager.cpp.
References TUIO::TuioPoint::getDistance().
getFrameID()
long TuioManager::getFrameID ()
Returns the current frame ID for external use.
Returns
the current frame ID for external use
Definition at line 413 of file TuioManager.cpp.
getFrameTime()
TuioTime TuioManager::getFrameTime ()
Returns the current frame ID for external use.
Returns
the current frame ID for external use
Definition at line 417 of file TuioManager.cpp.
getSessionID()
long TuioManager::getSessionID ()
Returns the next available Session ID for external use.
Returns
the next available Session ID for external use
Definition at line 408 of file TuioManager.cpp.
getTuioBlob()
TuioBlob * TuioDispatcher::getTuioBlob (long s_id) inherited
Returns the TuioBlob corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioBlob
Returns
an active TuioBlob corresponding to the provided Session ID or NULL
Definition at line 138 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
getTuioBlobCount()
int TuioDispatcher::getTuioBlobCount () inherited
Returns the number of all currently active TuioBlobs
Returns
the of all currently active TuioBlobs
Definition at line 185 of file TuioDispatcher.cpp.
getTuioBlobs()
std::list< TuioBlob * > TuioDispatcher::getTuioBlobs () inherited
Returns a List of all currently active TuioBlobs
Returns
a List of all currently active TuioBlobs
Definition at line 168 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockBlobList(), and TUIO::TuioDispatcher::unlockBlobList().
Referenced by TUIO::TuioClient::getTuioBlobs().
getTuioCursor()
TuioCursor * TuioDispatcher::getTuioCursor (long s_id) inherited
Returns the TuioCursor corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioCursor
Returns
an active TuioCursor corresponding to the provided Session ID or NULL
Definition at line 126 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
getTuioCursorCount()
int TuioDispatcher::getTuioCursorCount () inherited
Returns the number of all currently active TuioCursors
Returns
the of all currently active TuioCursors
Definition at line 181 of file TuioDispatcher.cpp.
getTuioCursors()
std::list< TuioCursor * > TuioDispatcher::getTuioCursors () inherited
Returns a List of all currently active TuioCursors
Returns
a List of all currently active TuioCursors
Definition at line 159 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockCursorList(), and TUIO::TuioDispatcher::unlockCursorList().
Referenced by TUIO::TuioClient::getTuioCursors().
getTuioObject()
TuioObject * TuioDispatcher::getTuioObject (long s_id) inherited
Returns the TuioObject corresponding to the provided Session ID or NULL if the Session ID does not refer to an active TuioObject
Returns
an active TuioObject corresponding to the provided Session ID or NULL
Definition at line 114 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
getTuioObjectCount()
int TuioDispatcher::getTuioObjectCount () inherited
Returns the number of all currently active TuioObjects
Returns
the of all currently active TuioObjects
Definition at line 177 of file TuioDispatcher.cpp.
getTuioObjects()
std::list< TuioObject * > TuioDispatcher::getTuioObjects () inherited
Returns a List of all currently active TuioObjects
Returns
a List of all currently active TuioObjects
Definition at line 150 of file TuioDispatcher.cpp.
References TUIO::TuioDispatcher::lockObjectList(), and TUIO::TuioDispatcher::unlockObjectList().
Referenced by TUIO::TuioClient::getTuioObjects().
getUntouchedBlobs()
std::list< TuioBlob * > TuioManager::getUntouchedBlobs ()
Returns a List of all currently inactive TuioBlobs
Returns
a List of all currently inactive TuioBlobs
Definition at line 573 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime().
getUntouchedCursors()
std::list< TuioCursor * > TuioManager::getUntouchedCursors ()
Returns a List of all currently inactive TuioCursors
Returns
a List of all currently inactive TuioCursors
Definition at line 526 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime().
getUntouchedObjects()
std::list< TuioObject * > TuioManager::getUntouchedObjects ()
Returns a List of all currently inactive TuioObjects
Returns
a List of all currently inactive TuioObjects
Definition at line 479 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime().
initFrame()
void TuioManager::initFrame (TuioTime ttime)
Initializes a new frame with the given TuioTime
Parameters
ttime the frame time
Definition at line 421 of file TuioManager.cpp.
Referenced by TUIO::TuioServer::~TuioServer().
lockBlobList()
void TuioDispatcher::lockBlobList () inherited
Locks the TuioBlob list in order to avoid updates during access
Definition at line 85 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioBlobs(), TUIO::TuioClient::copyTuioBlobs(), TUIO::TuioClient::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlobs(), and TUIO::TuioClient::getTuioBlobs().
lockCursorList()
void TuioDispatcher::lockCursorList () inherited
Locks the TuioCursor list in order to avoid updates during access
Definition at line 69 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioCursors(), TUIO::TuioClient::copyTuioCursors(), TUIO::TuioClient::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursors(), and TUIO::TuioClient::getTuioCursors().
lockObjectList()
void TuioDispatcher::lockObjectList () inherited
Locks the TuioObject list in order to avoid updates during access
Definition at line 53 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioDispatcher::copyTuioObjects(), TUIO::TuioClient::copyTuioObjects(), TUIO::TuioClient::getTuioObject(), TUIO::TuioDispatcher::getTuioObject(), TUIO::TuioDispatcher::getTuioObjects(), and TUIO::TuioClient::getTuioObjects().
removeAllTuioListeners()
void TuioDispatcher::removeAllTuioListeners () inherited
Removes all TuioListener from the list of registered TUIO event listeners
Definition at line 110 of file TuioDispatcher.cpp.
removeExternalTuioBlob()
void TuioManager::removeExternalTuioBlob (TuioBlob * tblb)
Removes an externally managed TuioBlob from the TuioServer's internal list of TuioBlob The referenced TuioBlob is not deleted
Parameters
tblb the TuioBlob to remove
Definition at line 395 of file TuioManager.cpp.
References TUIO::TuioBlob::getBlobID(), and TUIO::TuioContainer::getSessionID().
removeExternalTuioCursor()
void TuioManager::removeExternalTuioCursor (TuioCursor * tcur)
Removes an externally managed TuioCursor from the TuioServer's internal list of TuioCursor The referenced TuioCursor is not deleted
Parameters
tcur the TuioCursor to remove
Definition at line 246 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), and TUIO::TuioContainer::getSessionID().
removeExternalTuioObject()
void TuioManager::removeExternalTuioObject (TuioObject * tobj)
Removes an externally managed TuioObject from the TuioServer's internal list of TuioObjects The referenced TuioObject is not deleted
Parameters
tobj the TuioObject to remove
Definition at line 116 of file TuioManager.cpp.
References TUIO::TuioContainer::getSessionID(), and TUIO::TuioObject::getSymbolID().
removeTuioBlob()
void TuioManager::removeTuioBlob (TuioBlob * tblb)
Removes the referenced TuioBlob from the TuioServer's internal list of TuioBlobs and deletes the referenced TuioBlob afterwards
Parameters
tblb the TuioBlob to remove
Definition at line 349 of file TuioManager.cpp.
References TUIO::TuioBlob::getBlobID(), TUIO::TuioContainer::getSessionID(), and TUIO::TuioContainer::remove().
Referenced by removeUntouchedStoppedBlobs().
removeTuioCursor()
void TuioManager::removeTuioCursor (TuioCursor * tcur)
Removes the referenced TuioCursor from the TuioServer's internal list of TuioCursors and deletes the referenced TuioCursor afterwards
Parameters
tcur the TuioCursor to remove
Definition at line 201 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getSessionID(), and TUIO::TuioContainer::remove().
Referenced by removeUntouchedStoppedCursors().
removeTuioListener()
void TuioDispatcher::removeTuioListener (TuioListener * listener) inherited
Removes the provided TuioListener from the list of registered TUIO event listeners
Parameters
listener the TuioListener to remove
Definition at line 105 of file TuioDispatcher.cpp.
removeTuioObject()
void TuioManager::removeTuioObject (TuioObject * tobj)
Removes the referenced TuioObject from the TuioServer's internal list of TuioObjects and deletes the referenced TuioObject afterwards
Parameters
tobj the TuioObject to remove
Definition at line 102 of file TuioManager.cpp.
References TUIO::TuioContainer::getSessionID(), and TUIO::TuioObject::getSymbolID().
Referenced by removeUntouchedStoppedObjects().
removeUntouchedStoppedBlobs()
void TuioManager::removeUntouchedStoppedBlobs ()
Removes all currently inactive TuioCursors from the TuioServer's internal list of TuioBlobs
Definition at line 598 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime(), TUIO::TuioBlob::isMoving(), and removeTuioBlob().
Referenced by TUIO::TuioServer::~TuioServer().
removeUntouchedStoppedCursors()
void TuioManager::removeUntouchedStoppedCursors ()
Removes all currently inactive TuioCursors from the TuioServer's internal list of TuioCursors
Definition at line 551 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime(), TUIO::TuioContainer::isMoving(), and removeTuioCursor().
Referenced by TUIO::TuioServer::~TuioServer().
removeUntouchedStoppedObjects()
void TuioManager::removeUntouchedStoppedObjects ()
Removes all currently inactive TuioObjects from the TuioServer's internal list of TuioObjects
Definition at line 505 of file TuioManager.cpp.
References TUIO::TuioPoint::getTuioTime(), TUIO::TuioObject::isMoving(), and removeTuioObject().
Referenced by TUIO::TuioServer::~TuioServer().
setVerbose()
void TUIO::TuioManager::setVerbose (bool verbose) inline
The TuioServer prints verbose TUIO event messages to the console if set to true.
Parameters
verbose print verbose messages if set to true
Definition at line 347 of file TuioManager.h.
stopUntouchedMovingBlobs()
void TuioManager::stopUntouchedMovingBlobs ()
Calculates speed and acceleration values for all currently inactive TuioBlobs
Definition at line 583 of file TuioManager.cpp.
References TUIO::TuioBlob::getAngle(), TUIO::TuioBlob::getArea(), TUIO::TuioBlob::getBlobID(), TUIO::TuioBlob::getHeight(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioBlob::getRotationAccel(), TUIO::TuioBlob::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioBlob::getWidth(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioBlob::isMoving(), and TUIO::TuioBlob::stop().
Referenced by TUIO::TuioServer::~TuioServer().
stopUntouchedMovingCursors()
void TuioManager::stopUntouchedMovingCursors ()
Calculates speed and acceleration values for all currently inactive TuioCursors
Definition at line 536 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioContainer::isMoving(), and TUIO::TuioContainer::stop().
Referenced by TUIO::TuioServer::~TuioServer().
stopUntouchedMovingObjects()
void TuioManager::stopUntouchedMovingObjects ()
Calculates speed and acceleration values for all currently inactive TuioObjects
Definition at line 489 of file TuioManager.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioObject::getRotationAccel(), TUIO::TuioObject::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioObject::isMoving(), and TUIO::TuioObject::stop().
Referenced by TUIO::TuioServer::~TuioServer().
unlockBlobList()
void TuioDispatcher::unlockBlobList () inherited
Releases the lock of the TuioBlob list
Definition at line 93 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioClient::connect(), TUIO::TuioDispatcher::copyTuioBlobs(), TUIO::TuioClient::copyTuioBlobs(), TUIO::TuioClient::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlob(), TUIO::TuioDispatcher::getTuioBlobs(), and TUIO::TuioClient::getTuioBlobs().
unlockCursorList()
void TuioDispatcher::unlockCursorList () inherited
Releases the lock of the TuioCursor list
Definition at line 77 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioClient::connect(), TUIO::TuioDispatcher::copyTuioCursors(), TUIO::TuioClient::copyTuioCursors(), TUIO::TuioClient::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursor(), TUIO::TuioDispatcher::getTuioCursors(), and TUIO::TuioClient::getTuioCursors().
unlockObjectList()
void TuioDispatcher::unlockObjectList () inherited
Releases the lock of the TuioObject list
Definition at line 61 of file TuioDispatcher.cpp.
Referenced by TUIO::TuioClient::connect(), TUIO::TuioDispatcher::copyTuioObjects(), TUIO::TuioClient::copyTuioObjects(), TUIO::TuioClient::getTuioObject(), TUIO::TuioDispatcher::getTuioObject(), TUIO::TuioDispatcher::getTuioObjects(), and TUIO::TuioClient::getTuioObjects().
updateExternalTuioBlob()
void TuioManager::updateExternalTuioBlob (TuioBlob * tblb)
Updates an externally managed TuioBlob
Parameters
tblb the TuioBlob to update
Definition at line 335 of file TuioManager.cpp.
References TUIO::TuioBlob::getAngle(), TUIO::TuioBlob::getArea(), TUIO::TuioBlob::getBlobID(), TUIO::TuioBlob::getHeight(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioBlob::getRotationAccel(), TUIO::TuioBlob::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioBlob::getWidth(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), and TUIO::TuioBlob::isMoving().
updateExternalTuioCursor()
void TuioManager::updateExternalTuioCursor (TuioCursor * tcur)
Updates an externally managed TuioCursor
Parameters
tcur the TuioCursor to update
Definition at line 187 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), and TUIO::TuioContainer::isMoving().
updateExternalTuioObject()
void TuioManager::updateExternalTuioObject (TuioObject * tobj)
Updates an externally managed TuioObject
Parameters
tobj the TuioObject to update
Definition at line 88 of file TuioManager.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioObject::getRotationAccel(), TUIO::TuioObject::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), and TUIO::TuioObject::isMoving().
updateTuioBlob()
void TuioManager::updateTuioBlob (TuioBlob * tblb, float xp, float yp, float angle, float width, float height, float area)
Updates the referenced TuioBlob based on the given arguments.
Parameters
tblb the TuioObject to update
xp the X coordinate to assign
yp the Y coordinate to assign
angle the angle to assign
width the width to assign
height the height to assign
area the area to assign
Definition at line 319 of file TuioManager.cpp.
References TUIO::TuioBlob::getAngle(), TUIO::TuioBlob::getArea(), TUIO::TuioBlob::getBlobID(), TUIO::TuioBlob::getHeight(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioBlob::getRotationAccel(), TUIO::TuioBlob::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioBlob::getWidth(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioBlob::isMoving(), and TUIO::TuioBlob::update().
updateTuioCursor()
void TuioManager::updateTuioCursor (TuioCursor * tcur, float xp, float yp)
Updates the referenced TuioCursor based on the given arguments.
Parameters
tcur the TuioObject to update
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 171 of file TuioManager.cpp.
References TUIO::TuioCursor::getCursorID(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getSessionID(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioContainer::isMoving(), and TUIO::TuioCursor::update().
updateTuioObject()
void TuioManager::updateTuioObject (TuioObject * tobj, float xp, float yp, float a)
Updates the referenced TuioObject based on the given arguments.
Parameters
tobj the TuioObject to update
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
Definition at line 72 of file TuioManager.cpp.
References TUIO::TuioObject::getAngle(), TUIO::TuioContainer::getMotionAccel(), TUIO::TuioObject::getRotationAccel(), TUIO::TuioObject::getRotationSpeed(), TUIO::TuioContainer::getSessionID(), TUIO::TuioObject::getSymbolID(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioPoint::getX(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioObject::isMoving(), and TUIO::TuioObject::update().
The documentation for this class was generated from the following files:
vendor/TUIO/TUIO/TuioManager.h
vendor/TUIO/TUIO/TuioManager.cpp