Multi User Multi Touch Exercise: TUIO::TuioTime Class Reference
TUIO::TuioTime Class Reference
#include <TuioTime.h>
Public Member Functions
TuioTime ()
~TuioTime ()
TuioTime (long msec)
TuioTime (long sec, long usec)
TuioTime operator+ (long us)
TuioTime operator+ (TuioTime ttime)
TuioTime operator- (long us)
TuioTime operator- (TuioTime ttime)
void operator= (TuioTime ttime)
bool operator== (TuioTime ttime)
bool operator!= (TuioTime ttime)
void reset ()
long getSeconds () const
long getMicroseconds () const
long getTotalMilliseconds () const
Static Public Member Functions
static void initSession ()
static TuioTime getSessionTime ()
static TuioTime getStartTime ()
static TuioTime getSystemTime ()
Detailed Description
The TuioTime class is a simple structure that is used to reprent the time that has elapsed since the session start. The time is internally represented as seconds and fractions of microseconds which should be more than sufficient for gesture related timing requirements. Therefore at the beginning of a typical TUIO session the static method initSession() will set the reference time for the session. Another important static method getSessionTime will return a TuioTime object representing the time elapsed since the session start. The class also provides various addtional convience method, which allow some simple time arithmetics.
Author
Martin Kaltenbrunner
Version
1.1.6
Definition at line 48 of file TuioTime.h.
Constructor & Destructor Documentation
TuioTime() [1/3]
TUIO::TuioTime::TuioTime () inline
The default constructor takes no arguments and sets
the Seconds and Microseconds attributes of the newly created TuioTime both to zero.
Definition at line 62 of file TuioTime.h.
Referenced by getStartTime(), operator+(), and operator-().
~TuioTime()
TUIO::TuioTime::~TuioTime () inline
The destructor is doing nothing in particular.
Definition at line 67 of file TuioTime.h.
TuioTime() [2/3]
TuioTime::TuioTime (long msec)
This constructor takes the provided time represented in total Milliseconds and assigs this value to the newly created TuioTime.
Parameters
msec the total time in Millseconds
Definition at line 25 of file TuioTime.cpp.
TuioTime() [3/3]
TuioTime::TuioTime (long sec, long usec)
This constructor takes the provided time represented in Seconds and Microseconds
and assigs these value to the newly created TuioTime.
Parameters
sec the total time in seconds
usec the microseconds time component
Definition at line 30 of file TuioTime.cpp.
Member Function Documentation
getMicroseconds()
long TuioTime::getMicroseconds () const
Returns the TuioTime Microseconds component.
Returns
the TuioTime Microseconds component
Definition at line 97 of file TuioTime.cpp.
Referenced by initSession(), operator!=(), operator+(), operator-(), operator=(), and operator==().
getSeconds()
long TuioTime::getSeconds () const
Returns the TuioTime Seconds component.
Returns
the TuioTime Seconds component
Definition at line 93 of file TuioTime.cpp.
Referenced by TUIO::TuioServer::commitFrame(), initSession(), operator!=(), operator+(), operator-(), operator=(), and operator==().
getSessionTime()
TuioTime TuioTime::getSessionTime () static
Returns the present TuioTime representing the time since session start.
Returns
the present TuioTime representing the time since session start
Definition at line 111 of file TuioTime.cpp.
References getStartTime(), and getSystemTime().
Referenced by TUIO::TuioPoint::TuioPoint(), and TUIO::TuioServer::~TuioServer().
getStartTime()
TuioTime TuioTime::getStartTime () static
Returns the absolut TuioTime representing the session start.
Returns
the absolut TuioTime representing the session start
Definition at line 115 of file TuioTime.cpp.
References TuioTime().
Referenced by getSessionTime().
getSystemTime()
TuioTime TuioTime::getSystemTime () static
Returns the absolut TuioTime representing the current system time.
Returns
the absolut TuioTime representing the current system time
Definition at line 119 of file TuioTime.cpp.
Referenced by getSessionTime(), and initSession().
getTotalMilliseconds()
long TuioTime::getTotalMilliseconds () const
Returns the total TuioTime in Milliseconds.
Returns
the total TuioTime in Milliseconds
Definition at line 101 of file TuioTime.cpp.
Referenced by TUIO::TuioContainer::update(), TUIO::TuioPoint::update(), TUIO::TuioObject::update(), and TUIO::TuioBlob::update().
initSession()
void TuioTime::initSession () static
This static method globally resets the TUIO session time.
Definition at line 105 of file TuioTime.cpp.
References getMicroseconds(), getSeconds(), and getSystemTime().
Referenced by TUIO::TuioClient::connect().
operator!=()
bool TuioTime::operator!= (TuioTime ttime)
Takes a TuioTime argument and compares the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to compare
Returns
true if the two TuioTime have differnt Seconds or Microseconds attributes
Definition at line 83 of file TuioTime.cpp.
References getMicroseconds(), and getSeconds().
operator+() [1/2]
TuioTime TuioTime::operator+ (long us)
Sums the provided time value represented in total Microseconds to this TuioTime.
Parameters
us the total time to add in Microseconds
Returns
the sum of this TuioTime with the provided argument in microseconds
Definition at line 35 of file TuioTime.cpp.
References TuioTime().
operator+() [2/2]
TuioTime TuioTime::operator+ (TuioTime ttime)
Sums the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to add
Returns
the sum of this TuioTime with the provided TuioTime argument
Definition at line 41 of file TuioTime.cpp.
References getMicroseconds(), getSeconds(), and TuioTime().
operator-() [1/2]
TuioTime TuioTime::operator- (long us)
Subtracts the provided time represented in Microseconds from the private Seconds and Microseconds attributes.
Parameters
us the total time to subtract in Microseconds
Returns
the subtraction result of this TuioTime minus the provided time in Microseconds
Definition at line 49 of file TuioTime.cpp.
References TuioTime().
operator-() [2/2]
TuioTime TuioTime::operator- (TuioTime ttime)
Subtracts the provided TuioTime from the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to subtract
Returns
the subtraction result of this TuioTime minus the provided TuioTime
Definition at line 61 of file TuioTime.cpp.
References getMicroseconds(), getSeconds(), and TuioTime().
operator=()
void TuioTime::operator= (TuioTime ttime)
Assigns the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to assign
Definition at line 73 of file TuioTime.cpp.
References getMicroseconds(), and getSeconds().
operator==()
bool TuioTime::operator== (TuioTime ttime)
Takes a TuioTime argument and compares the provided TuioTime to the private Seconds and Microseconds attributes.
Parameters
ttime the TuioTime to compare
Returns
true if the two TuioTime have equal Seconds and Microseconds attributes
Definition at line 78 of file TuioTime.cpp.
References getMicroseconds(), and getSeconds().
reset()
void TuioTime::reset ()
Resets the seconds and micro_seconds attributes to zero.
Definition at line 88 of file TuioTime.cpp.
Referenced by TUIO::TuioClient::connect().
The documentation for this class was generated from the following files:
vendor/TUIO/TUIO/TuioTime.h
vendor/TUIO/TUIO/TuioTime.cpp