Multi User Multi Touch Exercise: TUIO::TuioPoint Class Reference
TUIO::TuioPoint Class Reference
#include <TuioPoint.h>
Public Member Functions
TuioPoint (float xp, float yp)
TuioPoint (TuioTime ttime, float xp, float yp)
TuioPoint (TuioPoint *tpoint)
virtual ~TuioPoint ()
void update (TuioPoint *tpoint)
void update (float xp, float yp)
void update (TuioTime ttime, float xp, float yp)
float getX () const
float getY () const
float getDistance (float xp, float yp) const
float getScreenDistance (float xp, float yp, int w, int h) const
float getDistance (TuioPoint *tpoint) const
float getAngle (float xp, float yp) const
float getAngle (TuioPoint *tpoint) const
float getAngleDegrees (float xp, float yp) const
float getAngleDegrees (TuioPoint *tpoint) const
int getScreenX (int width) const
int getScreenY (int height) const
TuioTime getTuioTime () const
TuioTime getStartTime () const
void addPositionThreshold (float thresh)
void removePositionThreshold ()
void addPositionFilter (float mcut, float beta)
void removePositionFilter ()
Protected Attributes
float xpos
float ypos
TuioTime currentTime
TuioTime startTime
OneEuroFilter * xposFilter
OneEuroFilter * yposFilter
float posThreshold
Detailed Description
The TuioPoint class on the one hand is a simple container and utility class to handle TUIO positions in general, on the other hand the TuioPoint is the base class for the TuioCursor and TuioObject classes.
Author
Martin Kaltenbrunner
Version
1.1.6
Definition at line 36 of file TuioPoint.h.
Constructor & Destructor Documentation
TuioPoint() [1/3]
TuioPoint::TuioPoint (float xp, float yp)
The default constructor takes no arguments and sets its coordinate attributes to zero and its time stamp to the current session time.
Definition at line 23 of file TuioPoint.cpp.
References currentTime, TUIO::TuioTime::getSessionTime(), startTime, xpos, and ypos.
TuioPoint() [2/3]
TuioPoint::TuioPoint (TuioTime ttime, float xp, float yp)
This constructor takes a TuioTime object and two floating point coordinate arguments and sets its coordinate attributes to these values and its time stamp to the provided TUIO time object.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 35 of file TuioPoint.cpp.
References currentTime, startTime, xpos, and ypos.
TuioPoint() [3/3]
TuioPoint::TuioPoint (TuioPoint * tpoint)
This constructor takes a TuioPoint argument and sets its coordinate attributes to the coordinates of the provided TuioPoint and its time stamp to the current session time.
Parameters
tpoint the TuioPoint to assign
Definition at line 47 of file TuioPoint.cpp.
References currentTime, TUIO::TuioTime::getSessionTime(), getX(), getY(), startTime, xpos, and ypos.
~TuioPoint()
virtual TUIO::TuioPoint::~TuioPoint () inline virtual
The destructor is doing nothing in particular.
Definition at line 88 of file TuioPoint.h.
Member Function Documentation
getAngle() [1/2]
float TuioPoint::getAngle (float xp, float yp) const
Returns the angle to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the angle to the provided coordinates
Definition at line 114 of file TuioPoint.cpp.
References getDistance(), xpos, and ypos.
Referenced by getAngle(), and getAngleDegrees().
getAngle() [2/2]
float TuioPoint::getAngle (TuioPoint * tpoint) const
Returns the angle to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the angle to the provided TuioPoint
Definition at line 125 of file TuioPoint.cpp.
References getAngle(), getX(), and getY().
getAngleDegrees() [1/2]
float TuioPoint::getAngleDegrees (float xp, float yp) const
Returns the angle in degrees to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the angle in degrees to the provided TuioPoint
Definition at line 129 of file TuioPoint.cpp.
References getAngle().
getAngleDegrees() [2/2]
float TuioPoint::getAngleDegrees (TuioPoint * tpoint) const
Returns the angle in degrees to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the angle in degrees to the provided TuioPoint
Definition at line 133 of file TuioPoint.cpp.
References getAngle().
getDistance() [1/2]
float TuioPoint::getDistance (float xp, float yp) const
Returns the distance to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the distance to the provided coordinates
Definition at line 97 of file TuioPoint.cpp.
References xpos.
Referenced by getAngle(), TUIO::TuioManager::getClosestTuioBlob(), TUIO::TuioManager::getClosestTuioCursor(), TUIO::TuioManager::getClosestTuioObject(), and getDistance().
getDistance() [2/2]
float TuioPoint::getDistance (TuioPoint * tpoint) const
Returns the distance to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the distance to the provided TuioPoint
Definition at line 109 of file TuioPoint.cpp.
References getDistance(), getX(), and getY().
getScreenDistance()
float TuioPoint::getScreenDistance (float xp, float yp, int w, int h) const
Returns the distance to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the distance to the provided coordinates
Definition at line 103 of file TuioPoint.cpp.
References xpos, and ypos.
getScreenX()
int TuioPoint::getScreenX (int width) const
Returns the X coordinate in pixels relative to the provided screen width.
Parameters
width the screen width
Returns
the X coordinate of this TuioPoint in pixels relative to the provided screen width
Definition at line 137 of file TuioPoint.cpp.
References xpos.
getStartTime()
TuioTime TuioPoint::getStartTime () const
Returns the start time of this TuioPoint as TuioTime.
Returns
the start time of this TuioPoint as TuioTime
Definition at line 149 of file TuioPoint.cpp.
References startTime.
getTuioTime()
TuioTime TuioPoint::getTuioTime () const
Returns current time stamp of this TuioPoint as TuioTime
Returns
the time stamp of this TuioPoint as TuioTime
Definition at line 145 of file TuioPoint.cpp.
References currentTime.
Referenced by TUIO::TuioServer::commitFrame(), TUIO::TuioManager::getUntouchedBlobs(), TUIO::TuioManager::getUntouchedCursors(), TUIO::TuioManager::getUntouchedObjects(), TUIO::TuioManager::removeUntouchedStoppedBlobs(), TUIO::TuioManager::removeUntouchedStoppedCursors(), TUIO::TuioManager::removeUntouchedStoppedObjects(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::update(), TUIO::TuioObject::update(), TUIO::TuioBlob::update(), TUIO::TuioManager::updateTuioBlob(), and TUIO::TuioManager::updateTuioObject().
getX()
float TuioPoint::getX () const
Returns the X coordinate of this TuioPoint.
Returns
the X coordinate of this TuioPoint
Definition at line 89 of file TuioPoint.cpp.
References xpos.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), TUIO::TuioManager::addExternalTuioObject(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::addTuioCursor(), TUIO::TuioManager::addTuioObject(), getAngle(), getDistance(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TuioPoint(), update(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getY()
float TuioPoint::getY () const
Returns the Y coordinate of this TuioPoint.
Returns
the Y coordinate of this TuioPoint
Definition at line 93 of file TuioPoint.cpp.
References ypos.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), TUIO::TuioManager::addExternalTuioObject(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::addTuioCursor(), TUIO::TuioManager::addTuioObject(), getAngle(), getDistance(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TuioPoint(), update(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
update() [1/3]
void TuioPoint::update (float xp, float yp)
Takes two floating point coordinate arguments and updates its coordinate attributes to the coordinates of the provided TuioPoint and leaves its time stamp unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 64 of file TuioPoint.cpp.
References xpos, and ypos.
update() [2/3]
void TuioPoint::update (TuioPoint * tpoint)
Takes a TuioPoint argument and updates its coordinate attributes to the coordinates of the provided TuioPoint and leaves its time stamp unchanged.
Parameters
tpoint the TuioPoint to assign
Definition at line 59 of file TuioPoint.cpp.
References getX(), getY(), xpos, and ypos.
Referenced by TUIO::TuioContainer::update().
update() [3/3]
void TuioPoint::update (TuioTime ttime, float xp, float yp)
Takes a TuioTime object and two floating point coordinate arguments and updates its coordinate attributes to the coordinates of the provided TuioPoint and its time stamp to the provided TUIO time object.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 69 of file TuioPoint.cpp.
References currentTime, TUIO::TuioTime::getTotalMilliseconds(), xpos, and ypos.
Member Data Documentation
currentTime
TuioTime TUIO::TuioPoint::currentTime protected
The time stamp of the last update represented as TuioTime (time since session start)
Definition at line 50 of file TuioPoint.h.
Referenced by getTuioTime(), TUIO::TuioContainer::remove(), TUIO::TuioContainer::TuioContainer(), TuioPoint(), TUIO::TuioContainer::update(), update(), TUIO::TuioObject::update(), and TUIO::TuioBlob::update().
startTime
TuioTime TUIO::TuioPoint::startTime protected
The creation time of this TuioPoint represented as TuioTime (time since session start)
Definition at line 54 of file TuioPoint.h.
Referenced by getStartTime(), and TuioPoint().
xpos
float TUIO::TuioPoint::xpos protected
X coordinate, representated as a floating point value in a range of 0..1
Definition at line 42 of file TuioPoint.h.
Referenced by getAngle(), getDistance(), TUIO::TuioContainer::getPosition(), getScreenDistance(), getScreenX(), getX(), TUIO::TuioBlob::stop(), TUIO::TuioContainer::stop(), TUIO::TuioObject::stop(), TUIO::TuioContainer::TuioContainer(), TuioPoint(), update(), and TUIO::TuioContainer::update().
ypos
float TUIO::TuioPoint::ypos protected
X coordinate, representated as a floating point value in a range of 0..1
Definition at line 46 of file TuioPoint.h.
Referenced by getAngle(), TUIO::TuioContainer::getPosition(), getScreenDistance(), getY(), TUIO::TuioBlob::stop(), TUIO::TuioContainer::stop(), TUIO::TuioObject::stop(), TUIO::TuioContainer::TuioContainer(), TuioPoint(), update(), and TUIO::TuioContainer::update().
The documentation for this class was generated from the following files:
vendor/TUIO/TUIO/TuioPoint.h
vendor/TUIO/TUIO/TuioPoint.cpp