Multi User Multi Touch Exercise: TUIO::TuioBlob Class Reference
TUIO::TuioBlob Class Reference
#include <TuioBlob.h>
Public Member Functions
TuioBlob (TuioTime ttime, long si, int bi, float xp, float yp, float a, float w, float h, float f)
TuioBlob (long si, int bi, float xp, float yp, float a, float w, float h, float f)
TuioBlob (TuioBlob *tblb)
virtual ~TuioBlob ()
int getBlobID () const
void setBlobID (int bi)
void update (TuioTime ttime, float xp, float yp, float a, float w, float h, float f, float xs, float ys, float rs, float ma, float ra)
void update (float xp, float yp, float a, float w, float h, float f, float xs, float ys, float rs, float ma, float ra)
void update (TuioTime ttime, float xp, float yp, float a, float w, float h, float f)
void stop (TuioTime ttime)
void update (TuioBlob *tblb)
float getWidth () const
float getHeight () const
int getScreenWidth (int w) const
int getScreenHeight (int h) const
float getArea () const
float getAngle () const
float getAngleDegrees () const
float getRotationSpeed () const
float getRotationAccel () const
bool isMoving () const
void addAngleThreshold (float thresh)
void removeAngleThreshold ()
void addAngleFilter (float mcut, float beta)
void removeAngleFilter ()
void addSizeThreshold (float thresh)
void removeSizeThreshold ()
void addSizeFilter (float mcut, float beta)
void removeSizeFilter ()
virtual void update (TuioTime ttime, float xp, float yp)
virtual void update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma)
virtual void update (float xp, float yp, float xs, float ys, float ma)
virtual void update (TuioContainer *tcon)
virtual void setTuioSource (int src_id, const char *src_name, const char *src_addr)
virtual const char * getTuioSourceName () const
virtual const char * getTuioSourceAddress () const
virtual int getTuioSourceID () const
virtual void update (TuioTime ttime, float xp, float yp)
virtual void update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma)
virtual void update (float xp, float yp, float xs, float ys, float ma)
virtual void update (TuioContainer *tcon)
void update (TuioPoint *tpoint)
void update (float xp, float yp)
virtual void remove (TuioTime ttime)
virtual long getSessionID () const
virtual void setSessionID (long s_id)
virtual float getXSpeed () const
virtual float getYSpeed () const
virtual TuioPoint getPosition () const
virtual std::list< TuioPoint > getPath () const
virtual float getMotionSpeed () const
virtual float getMotionAccel () const
virtual int getTuioState () const
virtual TuioPoint predictPosition ()
float getX () const
float getY () const
float getDistance (float xp, float yp) const
float getDistance (TuioPoint *tpoint) const
float getScreenDistance (float xp, float yp, int w, int h) const
float getAngle (float xp, float yp) const
float getAngle (TuioPoint *tpoint) const
float getAngleDegrees (float xp, float yp) const
float getAngleDegrees (TuioPoint *tpoint) const
int getScreenX (int width) const
int getScreenY (int height) const
TuioTime getTuioTime () const
TuioTime getStartTime () const
void addPositionThreshold (float thresh)
void removePositionThreshold ()
void addPositionFilter (float mcut, float beta)
void removePositionFilter ()
Protected Attributes
int blob_id
float angle
float width
float height
float area
float rotation_speed
float rotation_accel
float angleThreshold
OneEuroFilter * angleFilter
float sizeThreshold
OneEuroFilter * widthFilter
OneEuroFilter * heightFilter
long session_id
float x_speed
float y_speed
float motion_speed
float motion_accel
float x_accel
float y_accel
std::list< TuioPoint > path
int state
int source_id
std::string source_name
std::string source_addr
float xpos
float ypos
TuioTime currentTime
TuioTime startTime
OneEuroFilter * xposFilter
OneEuroFilter * yposFilter
float posThreshold
Detailed Description
The TuioBlob class encapsulates /tuio/2Dblb TUIO objects.
Author
Martin Kaltenbrunner
Version
1.1.6
Definition at line 32 of file TuioBlob.h.
Constructor & Destructor Documentation
TuioBlob() [1/3]
TuioBlob::TuioBlob (TuioTime ttime, long si, int bi, float xp, float yp, float a, float w, float h, float f)
This constructor takes a TuioTime argument and assigns it along with the provided Session ID, X and Y coordinate, width, height and angle to the newly created TuioBlob.
Parameters
ttime the TuioTime to assign
si the Session ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
w the width to assign
h the height to assign
f the area to assign
Definition at line 23 of file TuioBlob.cpp.
References angle, area, blob_id, height, rotation_accel, rotation_speed, and width.
TuioBlob() [2/3]
TuioBlob::TuioBlob (long si, int bi, float xp, float yp, float a, float w, float h, float f)
This constructor takes the provided Session ID, X and Y coordinate width, height and angle, and assigs these values to the newly created TuioBlob.
Parameters
si the Session ID to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
w the width to assign
h the height to assign
f the area to assign
Definition at line 39 of file TuioBlob.cpp.
References angle, area, blob_id, height, rotation_accel, rotation_speed, and width.
TuioBlob() [3/3]
TuioBlob::TuioBlob (TuioBlob * tblb)
This constructor takes the atttibutes of the provided TuioBlob and assigs these values to the newly created TuioBlob.
Parameters
tblb the TuioBlob to assign
Definition at line 55 of file TuioBlob.cpp.
References angle, area, blob_id, getAngle(), getArea(), getBlobID(), getHeight(), getWidth(), height, rotation_accel, rotation_speed, and width.
~TuioBlob()
virtual TUIO::TuioBlob::~TuioBlob () inline virtual
The destructor is doing nothing in particular.
Definition at line 113 of file TuioBlob.h.
Member Function Documentation
getAngle() [1/3]
float TuioBlob::getAngle () const
Returns the rotation angle of this TuioBlob.
Returns
the rotation angle of this TuioBlob
Definition at line 181 of file TuioBlob.cpp.
References angle.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TuioBlob(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getAngle() [2/3]
float TuioPoint::getAngle (float xp, float yp) const inherited
Returns the angle to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the angle to the provided coordinates
Definition at line 114 of file TuioPoint.cpp.
References TUIO::TuioPoint::getDistance(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
Referenced by TUIO::TuioPoint::getAngle(), and TUIO::TuioPoint::getAngleDegrees().
getAngle() [3/3]
float TuioPoint::getAngle (TuioPoint * tpoint) const inherited
Returns the angle to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the angle to the provided TuioPoint
Definition at line 125 of file TuioPoint.cpp.
References TUIO::TuioPoint::getAngle(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
getAngleDegrees() [1/3]
float TuioBlob::getAngleDegrees () const
Returns the rotation angle in degrees of this TuioBlob.
Returns
the rotation angle in degrees of this TuioBlob
Definition at line 185 of file TuioBlob.cpp.
References angle.
getAngleDegrees() [2/3]
float TuioPoint::getAngleDegrees (float xp, float yp) const inherited
Returns the angle in degrees to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the angle in degrees to the provided TuioPoint
Definition at line 129 of file TuioPoint.cpp.
References TUIO::TuioPoint::getAngle().
getAngleDegrees() [3/3]
float TuioPoint::getAngleDegrees (TuioPoint * tpoint) const inherited
Returns the angle in degrees to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the angle in degrees to the provided TuioPoint
Definition at line 133 of file TuioPoint.cpp.
References TUIO::TuioPoint::getAngle().
getArea()
float TuioBlob::getArea () const
Returns the area of this TuioBlob.
Returns
the area of this TuioBlob
Definition at line 177 of file TuioBlob.cpp.
References area.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TuioBlob(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getBlobID()
int TuioBlob::getBlobID () const
Returns the Blob ID of this TuioBlob.
Returns
the Blob ID of this TuioBlob
Definition at line 71 of file TuioBlob.cpp.
References blob_id.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::removeExternalTuioBlob(), TUIO::TuioManager::removeTuioBlob(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TuioBlob(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getDistance() [1/2]
float TuioPoint::getDistance (float xp, float yp) const inherited
Returns the distance to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the distance to the provided coordinates
Definition at line 97 of file TuioPoint.cpp.
References TUIO::TuioPoint::xpos.
Referenced by TUIO::TuioPoint::getAngle(), TUIO::TuioManager::getClosestTuioBlob(), TUIO::TuioManager::getClosestTuioCursor(), TUIO::TuioManager::getClosestTuioObject(), and TUIO::TuioPoint::getDistance().
getDistance() [2/2]
float TuioPoint::getDistance (TuioPoint * tpoint) const inherited
Returns the distance to the provided TuioPoint
Parameters
tpoint the distant TuioPoint
Returns
the distance to the provided TuioPoint
Definition at line 109 of file TuioPoint.cpp.
References TUIO::TuioPoint::getDistance(), TUIO::TuioPoint::getX(), and TUIO::TuioPoint::getY().
getHeight()
float TuioBlob::getHeight () const
Returns the height of this TuioBlob.
Returns
the height of this TuioBlob
Definition at line 165 of file TuioBlob.cpp.
References height.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TuioBlob(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getMotionAccel()
float TuioContainer::getMotionAccel () const virtual inherited
Returns the motion acceleration of this TuioContainer.
Returns
the motion acceleration of this TuioContainer
Definition at line 220 of file TuioContainer.cpp.
References TUIO::TuioContainer::motion_accel.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getMotionSpeed()
float TuioContainer::getMotionSpeed () const virtual inherited
Returns the motion speed of this TuioContainer.
Returns
the motion speed of this TuioContainer
Definition at line 216 of file TuioContainer.cpp.
References TUIO::TuioContainer::motion_speed.
Referenced by TUIO::TuioContainer::update().
getPath()
std::list< TuioPoint > TuioContainer::getPath () const virtual inherited
Returns the path of this TuioContainer.
Returns
the path of this TuioContainer
Definition at line 212 of file TuioContainer.cpp.
References TUIO::TuioContainer::path.
getPosition()
TuioPoint TuioContainer::getPosition () const virtual inherited
Returns the position of this TuioContainer.
Returns
the position of this TuioContainer
Definition at line 207 of file TuioContainer.cpp.
References TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
getRotationAccel()
float TuioBlob::getRotationAccel () const
Returns the rotation acceleration of this TuioBlob.
Returns
the rotation acceleration of this TuioBlob
Definition at line 193 of file TuioBlob.cpp.
References rotation_accel.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getRotationSpeed()
float TuioBlob::getRotationSpeed () const
Returns the rotation speed of this TuioBlob.
Returns
the rotation speed of this TuioBlob
Definition at line 189 of file TuioBlob.cpp.
References rotation_speed.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getScreenDistance()
float TuioPoint::getScreenDistance (float xp, float yp, int w, int h) const inherited
Returns the distance to the provided coordinates
Parameters
xp the X coordinate of the distant point
yp the Y coordinate of the distant point
Returns
the distance to the provided coordinates
Definition at line 103 of file TuioPoint.cpp.
References TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
getScreenHeight()
int TuioBlob::getScreenHeight (int h) const
Returns the height of this TuioBlob.
Returns
the height of this TuioBlob
Definition at line 173 of file TuioBlob.cpp.
References height.
getScreenWidth()
int TuioBlob::getScreenWidth (int w) const
Returns the width of this TuioBlob.
Returns
the width of this TuioBlob
Definition at line 169 of file TuioBlob.cpp.
References width.
getScreenX()
int TuioPoint::getScreenX (int width) const inherited
Returns the X coordinate in pixels relative to the provided screen width.
Parameters
width the screen width
Returns
the X coordinate of this TuioPoint in pixels relative to the provided screen width
Definition at line 137 of file TuioPoint.cpp.
References TUIO::TuioPoint::xpos.
getSessionID()
long TuioContainer::getSessionID () const virtual inherited
Returns the Session ID of this TuioContainer.
Returns
the Session ID of this TuioContainer
Definition at line 191 of file TuioContainer.cpp.
References TUIO::TuioContainer::session_id.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), TUIO::TuioManager::addExternalTuioObject(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::addTuioCursor(), TUIO::TuioManager::addTuioObject(), TUIO::TuioManager::removeExternalTuioBlob(), TUIO::TuioManager::removeExternalTuioCursor(), TUIO::TuioManager::removeExternalTuioObject(), TUIO::TuioManager::removeTuioBlob(), TUIO::TuioManager::removeTuioCursor(), TUIO::TuioManager::removeTuioObject(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::TuioContainer(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getStartTime()
TuioTime TuioPoint::getStartTime () const inherited
Returns the start time of this TuioPoint as TuioTime.
Returns
the start time of this TuioPoint as TuioTime
Definition at line 149 of file TuioPoint.cpp.
References TUIO::TuioPoint::startTime.
getTuioSourceAddress()
const char * TuioContainer::getTuioSourceAddress () const virtual inherited
Returns the address of the TUIO source
Definition at line 87 of file TuioContainer.cpp.
References TUIO::TuioContainer::source_addr.
getTuioSourceID()
int TuioContainer::getTuioSourceID () const virtual inherited
Returns the ID of the TUIO source
Definition at line 91 of file TuioContainer.cpp.
References TUIO::TuioContainer::source_id.
Referenced by TUIO::TuioClient::copyTuioBlobs(), TUIO::TuioClient::copyTuioCursors(), TUIO::TuioClient::copyTuioObjects(), TUIO::TuioClient::getTuioBlobs(), TUIO::TuioClient::getTuioCursors(), and TUIO::TuioClient::getTuioObjects().
getTuioSourceName()
const char * TuioContainer::getTuioSourceName () const virtual inherited
Returns the name of the TUIO source
Definition at line 83 of file TuioContainer.cpp.
References TUIO::TuioContainer::source_name.
getTuioState()
int TuioContainer::getTuioState () const virtual inherited
Returns the TUIO state of this TuioContainer.
Returns
the TUIO state of this TuioContainer
Definition at line 224 of file TuioContainer.cpp.
References TUIO::TuioContainer::state.
getTuioTime()
TuioTime TuioPoint::getTuioTime () const inherited
Returns current time stamp of this TuioPoint as TuioTime
Returns
the time stamp of this TuioPoint as TuioTime
Definition at line 145 of file TuioPoint.cpp.
References TUIO::TuioPoint::currentTime.
Referenced by TUIO::TuioServer::commitFrame(), TUIO::TuioManager::getUntouchedBlobs(), TUIO::TuioManager::getUntouchedCursors(), TUIO::TuioManager::getUntouchedObjects(), TUIO::TuioManager::removeUntouchedStoppedBlobs(), TUIO::TuioManager::removeUntouchedStoppedCursors(), TUIO::TuioManager::removeUntouchedStoppedObjects(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::update(), TUIO::TuioObject::update(), update(), TUIO::TuioManager::updateTuioBlob(), and TUIO::TuioManager::updateTuioObject().
getWidth()
float TuioBlob::getWidth () const
Returns the width of this TuioBlob.
Returns
the width of this TuioBlob
Definition at line 161 of file TuioBlob.cpp.
References width.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TuioBlob(), update(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
getX()
float TuioPoint::getX () const inherited
Returns the X coordinate of this TuioPoint.
Returns
the X coordinate of this TuioPoint
Definition at line 89 of file TuioPoint.cpp.
References TUIO::TuioPoint::xpos.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), TUIO::TuioManager::addExternalTuioObject(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::addTuioCursor(), TUIO::TuioManager::addTuioObject(), TUIO::TuioPoint::getAngle(), TUIO::TuioPoint::getDistance(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioPoint::TuioPoint(), TUIO::TuioPoint::update(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getXSpeed()
float TuioContainer::getXSpeed () const virtual inherited
Returns the X velocity of this TuioContainer.
Returns
the X velocity of this TuioContainer
Definition at line 199 of file TuioContainer.cpp.
References TUIO::TuioContainer::x_speed.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getY()
float TuioPoint::getY () const inherited
Returns the Y coordinate of this TuioPoint.
Returns
the Y coordinate of this TuioPoint
Definition at line 93 of file TuioPoint.cpp.
References TUIO::TuioPoint::ypos.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), TUIO::TuioManager::addExternalTuioObject(), TUIO::TuioManager::addTuioBlob(), TUIO::TuioManager::addTuioCursor(), TUIO::TuioManager::addTuioObject(), TUIO::TuioPoint::getAngle(), TUIO::TuioPoint::getDistance(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioPoint::TuioPoint(), TUIO::TuioPoint::update(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
getYSpeed()
float TuioContainer::getYSpeed () const virtual inherited
Returns the Y velocity of this TuioContainer.
Returns
the Y velocity of this TuioContainer
Definition at line 203 of file TuioContainer.cpp.
References TUIO::TuioContainer::y_speed.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::stopUntouchedMovingCursors(), TUIO::TuioManager::stopUntouchedMovingObjects(), TUIO::TuioContainer::update(), TUIO::TuioManager::updateExternalTuioBlob(), TUIO::TuioManager::updateExternalTuioCursor(), TUIO::TuioManager::updateExternalTuioObject(), TUIO::TuioManager::updateTuioBlob(), TUIO::TuioManager::updateTuioCursor(), and TUIO::TuioManager::updateTuioObject().
isMoving()
bool TuioBlob::isMoving () const virtual
Returns true of this TuioBlob is moving.
Returns
true of this TuioBlob is moving
Reimplemented from TUIO::TuioContainer.
Definition at line 197 of file TuioBlob.cpp.
References TUIO::TuioContainer::state.
Referenced by TUIO::TuioManager::removeUntouchedStoppedBlobs(), TUIO::TuioManager::stopUntouchedMovingBlobs(), TUIO::TuioManager::updateExternalTuioBlob(), and TUIO::TuioManager::updateTuioBlob().
remove()
void TuioContainer::remove (TuioTime ttime) virtual inherited
Assigns the REMOVE state to this TuioContainer and sets its TuioTime time stamp to the provided TuioTime argument.
Parameters
ttime the TuioTime to assign
Definition at line 186 of file TuioContainer.cpp.
References TUIO::TuioPoint::currentTime, and TUIO::TuioContainer::state.
Referenced by TUIO::TuioManager::removeTuioBlob(), and TUIO::TuioManager::removeTuioCursor().
setBlobID()
void TuioBlob::setBlobID (int bi)
Sets the Blob ID of this TuioBlob.
Parameters
bi the new Blob ID for this TuioBlob
Definition at line 75 of file TuioBlob.cpp.
References blob_id.
Referenced by TUIO::TuioManager::addExternalTuioBlob().
setSessionID()
void TuioContainer::setSessionID (long s_id) virtual inherited
Sets the Session ID of this TuioContainer.
Parameters
s_id the new Session ID for this TuioContainer
Definition at line 195 of file TuioContainer.cpp.
References TUIO::TuioContainer::session_id.
Referenced by TUIO::TuioManager::addExternalTuioBlob(), TUIO::TuioManager::addExternalTuioCursor(), and TUIO::TuioManager::addExternalTuioObject().
setTuioSource()
void TuioContainer::setTuioSource (int src_id, const char * src_name, const char * src_addr) virtual inherited
Sets the ID, name and address of the TUIO source
Parameters
src_id the ID of the TUIO source
src_name the name of the TUIO source
src_addr the address of the TUIO source
Definition at line 77 of file TuioContainer.cpp.
References TUIO::TuioContainer::source_addr, TUIO::TuioContainer::source_id, and TUIO::TuioContainer::source_name.
stop()
void TuioBlob::stop (TuioTime ttime) virtual
This method is used to calculate the speed and acceleration values of a TuioBlob with unchanged position and angle.
Reimplemented from TUIO::TuioContainer.
Definition at line 146 of file TuioBlob.cpp.
References angle, area, height, update(), width, TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
Referenced by TUIO::TuioManager::stopUntouchedMovingBlobs().
update() [1/14]
void TuioPoint::update (float xp, float yp) inherited
Takes two floating point coordinate arguments and updates its coordinate attributes to the coordinates of the provided TuioPoint and leaves its time stamp unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 64 of file TuioPoint.cpp.
References TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
update() [2/14]
void TuioBlob::update (float xp, float yp, float a, float w, float h, float f, float xs, float ys, float rs, float ma, float ra)
Assigns the provided X and Y coordinate, angle, X and Y velocity, motion acceleration rotation velocity and rotation acceleration to the private TuioContainer attributes. The TuioTime time stamp remains unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle to assign
w the width to assign
h the height to assign
f the area to assign
xs the X velocity to assign
ys the Y velocity to assign
rs the rotation velocity to assign
ma the motion acceleration to assign
ra the rotation acceleration to assign
Definition at line 90 of file TuioBlob.cpp.
References angle, area, height, rotation_accel, rotation_speed, TUIO::TuioContainer::state, TUIO::TuioContainer::update(), and width.
update() [3/14]
void TuioContainer::update
Assigns the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes. The TuioTime time stamp remains unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 197 of file TuioContainer.cpp.
update() [4/14]
void TuioContainer::update (float xp, float yp, float xs, float ys, float ma) virtual inherited
Assigns the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes. The TuioTime time stamp remains unchanged.
Parameters
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 148 of file TuioContainer.cpp.
References TUIO::TuioPoint::currentTime, TUIO::TuioContainer::motion_accel, TUIO::TuioContainer::motion_speed, TUIO::TuioContainer::path, TUIO::TuioContainer::state, TUIO::TuioPoint::update(), TUIO::TuioContainer::x_speed, TUIO::TuioPoint::xpos, TUIO::TuioContainer::y_speed, and TUIO::TuioPoint::ypos.
update() [5/14]
void TuioBlob::update (TuioBlob * tblb)
Takes the atttibutes of the provided TuioBlob and assigs these values to this TuioBlob. The TuioTime time stamp of this TuioContainer remains unchanged.
Parameters
tblb the TuioContainer to assign
Definition at line 150 of file TuioBlob.cpp.
References angle, area, getAngle(), getArea(), getHeight(), getRotationAccel(), getRotationSpeed(), getWidth(), height, rotation_accel, rotation_speed, TUIO::TuioContainer::state, TUIO::TuioContainer::update(), and width.
update() [6/14]
void TuioContainer::update
Takes the atttibutes of the provided TuioContainer and assigs these values to this TuioContainer. The TuioTime time stamp of this TuioContainer remains unchanged.
Parameters
tcon the TuioContainer to assign
Definition at line 206 of file TuioContainer.cpp.
update() [7/14]
void TuioContainer::update (TuioContainer * tcon) virtual inherited
Takes the atttibutes of the provided TuioContainer and assigs these values to this TuioContainer. The TuioTime time stamp of this TuioContainer remains unchanged.
Parameters
tcon the TuioContainer to assign
Definition at line 167 of file TuioContainer.cpp.
References TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::getMotionSpeed(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioContainer::getXSpeed(), TUIO::TuioContainer::getYSpeed(), TUIO::TuioContainer::motion_accel, TUIO::TuioContainer::motion_speed, TUIO::TuioContainer::path, TUIO::TuioContainer::state, TUIO::TuioPoint::update(), TUIO::TuioContainer::x_speed, TUIO::TuioPoint::xpos, TUIO::TuioContainer::y_speed, and TUIO::TuioPoint::ypos.
update() [8/14]
void TuioPoint::update (TuioPoint * tpoint) inherited
Takes a TuioPoint argument and updates its coordinate attributes to the coordinates of the provided TuioPoint and leaves its time stamp unchanged.
Parameters
tpoint the TuioPoint to assign
Definition at line 59 of file TuioPoint.cpp.
References TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), TUIO::TuioPoint::xpos, and TUIO::TuioPoint::ypos.
Referenced by TUIO::TuioContainer::update().
update() [9/14]
void TuioContainer::update
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate to the private TuioContainer attributes. The speed and accleration values are calculated accordingly.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 165 of file TuioContainer.cpp.
Referenced by stop().
update() [10/14]
void TuioContainer::update (TuioTime ttime, float xp, float yp) virtual inherited
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate to the private TuioContainer attributes. The speed and accleration values are calculated accordingly.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
Definition at line 95 of file TuioContainer.cpp.
References TUIO::TuioPoint::currentTime, TUIO::TuioTime::getTotalMilliseconds(), TUIO::TuioPoint::getTuioTime(), TUIO::TuioPoint::getX(), TUIO::TuioPoint::getY(), TUIO::TuioContainer::motion_accel, TUIO::TuioContainer::motion_speed, TUIO::TuioContainer::path, TUIO::TuioContainer::state, TUIO::TuioPoint::update(), TUIO::TuioContainer::x_speed, TUIO::TuioPoint::xpos, TUIO::TuioContainer::y_speed, and TUIO::TuioPoint::ypos.
update() [11/14]
void TuioBlob::update (TuioTime ttime, float xp, float yp, float a, float w, float h, float f)
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate and angle to the private TuioBlob attributes. The speed and accleration values are calculated accordingly.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the angle coordinate to assign
w the width to assign
h the height to assign
f the area to assign
Definition at line 101 of file TuioBlob.cpp.
References angle, area, TUIO::TuioPoint::currentTime, TUIO::TuioTime::getTotalMilliseconds(), TUIO::TuioPoint::getTuioTime(), height, TUIO::TuioContainer::path, rotation_accel, rotation_speed, TUIO::TuioContainer::state, TUIO::TuioContainer::update(), and width.
update() [12/14]
void TuioBlob::update (TuioTime ttime, float xp, float yp, float a, float w, float h, float f, float xs, float ys, float rs, float ma, float ra)
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate, angle, X and Y velocity, motion acceleration, rotation speed and rotation acceleration to the private TuioBlob attributes.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
a the rotation angle to assign
w the width to assign
h the height to assign
f the area to assign
xs the X velocity to assign
ys the Y velocity to assign
rs the rotation velocity to assign
ma the motion acceleration to assign
ra the rotation acceleration to assign
Definition at line 79 of file TuioBlob.cpp.
References angle, area, height, rotation_accel, rotation_speed, TUIO::TuioContainer::state, TUIO::TuioContainer::update(), and width.
Referenced by TUIO::TuioManager::updateTuioBlob().
update() [13/14]
void TuioContainer::update
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 185 of file TuioContainer.cpp.
update() [14/14]
void TuioContainer::update (TuioTime ttime, float xp, float yp, float xs, float ys, float ma) virtual inherited
Takes a TuioTime argument and assigns it along with the provided X and Y coordinate, X and Y velocity and acceleration to the private TuioContainer attributes.
Parameters
ttime the TuioTime to assign
xp the X coordinate to assign
yp the Y coordinate to assign
xs the X velocity to assign
ys the Y velocity to assign
ma the acceleration to assign
Definition at line 129 of file TuioContainer.cpp.
References TUIO::TuioPoint::currentTime, TUIO::TuioContainer::motion_accel, TUIO::TuioContainer::motion_speed, TUIO::TuioContainer::path, TUIO::TuioContainer::state, TUIO::TuioPoint::update(), TUIO::TuioContainer::x_speed, TUIO::TuioPoint::xpos, TUIO::TuioContainer::y_speed, and TUIO::TuioPoint::ypos.
Member Data Documentation
angle
float TUIO::TuioBlob::angle protected
The rotation angle value.
Definition at line 42 of file TuioBlob.h.
Referenced by getAngle(), getAngleDegrees(), stop(), TuioBlob(), and update().
area
float TUIO::TuioBlob::area protected
The area value.
Definition at line 54 of file TuioBlob.h.
Referenced by getArea(), stop(), TuioBlob(), and update().
blob_id
int TUIO::TuioBlob::blob_id protected
The individual blob ID number that is assigned to each TuioBlob.
Definition at line 38 of file TuioBlob.h.
Referenced by getBlobID(), setBlobID(), and TuioBlob().
currentTime
TuioTime TUIO::TuioPoint::currentTime protected inherited
The time stamp of the last update represented as TuioTime (time since session start)
Definition at line 50 of file TuioPoint.h.
Referenced by TUIO::TuioPoint::getTuioTime(), TUIO::TuioContainer::remove(), TUIO::TuioContainer::TuioContainer(), TUIO::TuioPoint::TuioPoint(), TUIO::TuioContainer::update(), TUIO::TuioPoint::update(), TUIO::TuioObject::update(), and update().
height
float TUIO::TuioBlob::height protected
The height value.
Definition at line 50 of file TuioBlob.h.
Referenced by getHeight(), getScreenHeight(), stop(), TuioBlob(), and update().
motion_accel
float TUIO::TuioContainer::motion_accel protected inherited
The motion acceleration value.
Definition at line 71 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getMotionAccel(), TUIO::TuioContainer::TuioContainer(), and TUIO::TuioContainer::update().
motion_speed
float TUIO::TuioContainer::motion_speed protected inherited
The motion speed value.
Definition at line 67 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getMotionSpeed(), TUIO::TuioContainer::TuioContainer(), and TUIO::TuioContainer::update().
path
std::list<TuioPoint> TUIO::TuioContainer::path protected inherited
A List of TuioPoints containing all the previous positions of the TUIO component.
Definition at line 77 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getPath(), TUIO::TuioContainer::TuioContainer(), TUIO::TuioContainer::update(), TUIO::TuioObject::update(), and update().
rotation_accel
float TUIO::TuioBlob::rotation_accel protected
The rotation acceleration value.
Definition at line 62 of file TuioBlob.h.
Referenced by getRotationAccel(), TuioBlob(), and update().
rotation_speed
float TUIO::TuioBlob::rotation_speed protected
The rotation speed value.
Definition at line 58 of file TuioBlob.h.
Referenced by getRotationSpeed(), TuioBlob(), and update().
session_id
long TUIO::TuioContainer::session_id protected inherited
The unique session ID number that is assigned to each TUIO object or cursor.
Definition at line 55 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getSessionID(), TUIO::TuioContainer::setSessionID(), and TUIO::TuioContainer::TuioContainer().
source_addr
std::string TUIO::TuioContainer::source_addr protected inherited
The address of the TUIO source
Definition at line 93 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getTuioSourceAddress(), and TUIO::TuioContainer::setTuioSource().
source_id
int TUIO::TuioContainer::source_id protected inherited
The ID of the TUIO source
Definition at line 85 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getTuioSourceID(), and TUIO::TuioContainer::setTuioSource().
source_name
std::string TUIO::TuioContainer::source_name protected inherited
The name of the TUIO source
Definition at line 89 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getTuioSourceName(), and TUIO::TuioContainer::setTuioSource().
startTime
TuioTime TUIO::TuioPoint::startTime protected inherited
The creation time of this TuioPoint represented as TuioTime (time since session start)
Definition at line 54 of file TuioPoint.h.
Referenced by TUIO::TuioPoint::getStartTime(), and TUIO::TuioPoint::TuioPoint().
state
int TUIO::TuioContainer::state protected inherited
Reflects the current state of the TuioComponent
Definition at line 81 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getTuioState(), isMoving(), TUIO::TuioContainer::isMoving(), TUIO::TuioObject::isMoving(), TUIO::TuioContainer::remove(), TUIO::TuioContainer::stop(), TUIO::TuioContainer::update(), update(), and TUIO::TuioObject::update().
width
float TUIO::TuioBlob::width protected
The width value.
Definition at line 46 of file TuioBlob.h.
Referenced by getScreenWidth(), getWidth(), stop(), TuioBlob(), and update().
x_speed
float TUIO::TuioContainer::x_speed protected inherited
The X-axis velocity value.
Definition at line 59 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getXSpeed(), TUIO::TuioContainer::TuioContainer(), and TUIO::TuioContainer::update().
xpos
float TUIO::TuioPoint::xpos protected inherited
X coordinate, representated as a floating point value in a range of 0..1
Definition at line 42 of file TuioPoint.h.
Referenced by TUIO::TuioPoint::getAngle(), TUIO::TuioPoint::getDistance(), TUIO::TuioContainer::getPosition(), TUIO::TuioPoint::getScreenDistance(), TUIO::TuioPoint::getScreenX(), TUIO::TuioPoint::getX(), stop(), TUIO::TuioContainer::stop(), TUIO::TuioObject::stop(), TUIO::TuioContainer::TuioContainer(), TUIO::TuioPoint::TuioPoint(), TUIO::TuioPoint::update(), and TUIO::TuioContainer::update().
y_speed
float TUIO::TuioContainer::y_speed protected inherited
The Y-axis velocity value.
Definition at line 63 of file TuioContainer.h.
Referenced by TUIO::TuioContainer::getYSpeed(), TUIO::TuioContainer::TuioContainer(), and TUIO::TuioContainer::update().
ypos
float TUIO::TuioPoint::ypos protected inherited
X coordinate, representated as a floating point value in a range of 0..1
Definition at line 46 of file TuioPoint.h.
Referenced by TUIO::TuioPoint::getAngle(), TUIO::TuioContainer::getPosition(), TUIO::TuioPoint::getScreenDistance(), TUIO::TuioPoint::getY(), stop(), TUIO::TuioContainer::stop(), TUIO::TuioObject::stop(), TUIO::TuioContainer::TuioContainer(), TUIO::TuioPoint::TuioPoint(), TUIO::TuioPoint::update(), and TUIO::TuioContainer::update().
The documentation for this class was generated from the following files:
vendor/TUIO/TUIO/TuioBlob.h
vendor/TUIO/TUIO/TuioBlob.cpp